// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.DAL.Models;

#nullable disable

namespace _1.DAL.Migrations
{
    [DbContext(typeof(BanGiayDBContext))]
    partial class BanGiayDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1.DAL.Models.BangChiTietSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("GiaBan");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(20,0)")
                        .HasColumnName("GiaNhap");

                    b.Property<Guid>("IdHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMauSac")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Mota");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasColumnName("Size");

                    b.Property<int>("Soluongton")
                        .HasColumnType("int")
                        .HasColumnName("Soluongton");

                    b.HasKey("Id");

                    b.HasIndex("IdHang");

                    b.HasIndex("IdLoai");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdSp");

                    b.ToTable("ChiTietSP", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MaCV");

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenCV");

                    b.HasKey("Id");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangDoiTra", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaDoi");

                    b.HasKey("Id");

                    b.ToTable("DoiTra", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangGioHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DiaChi");

                    b.Property<Guid>("IdKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MaGioHang");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayThanhToan");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("NguoiNhan");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("SDT");

                    b.Property<int>("TinhTrang")
                        .HasColumnType("int")
                        .HasColumnName("TinhTrang");

                    b.HasKey("Id");

                    b.HasIndex("IdKH");

                    b.HasIndex("IdNV");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangGioHangChiTiet", b =>
                {
                    b.Property<Guid>("IdCTSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGioHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdCTSP", "IdGioHang");

                    b.HasIndex("IdGioHang");

                    b.ToTable("GioHangCT", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangHangSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MaHang");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TenHang");

                    b.HasKey("Id");

                    b.ToTable("HangSP", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangHoaDon", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("DiaChi");

                    b.Property<Guid>("IdKH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaHD");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayNhan");

                    b.Property<DateTime>("NgayShip")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayShip");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayTao");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("DateTime")
                        .HasColumnName("NgayThanhToan");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("NguoiNhan");

                    b.Property<int>("TinhTrang")
                        .HasColumnType("int")
                        .HasColumnName("TinhTrang");

                    b.HasKey("id");

                    b.HasIndex("IdKH");

                    b.HasIndex("IdNV");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangHoaDonCT", b =>
                {
                    b.Property<Guid>("IDCTSP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal")
                        .HasColumnName("DonGia");

                    b.Property<Guid>("IDKM")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MoTa");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("IDCTSP", "IdHoaDon");

                    b.HasIndex("IDKM");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangKhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ho");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("MatKhau");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("Datetime")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ten");

                    b.Property<string>("TenDem")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenDem");

                    b.HasKey("Id");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangKhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MaKhuyenMai");

                    b.Property<string>("MotaKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MotaKM");

                    b.HasKey("Id");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangLoaiSP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MaLoai");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TenLoai");

                    b.HasKey("Id");

                    b.ToTable("LoaiSP", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangMauSac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaMs")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MaMS");

                    b.Property<string>("TenMs")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TenMS");

                    b.HasKey("Id");

                    b.ToTable("MauSac", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangNhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ho");

                    b.Property<Guid>("IdCV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ma");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("MatKhau");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("Datetime")
                        .HasColumnName("NgaySinh");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Ten");

                    b.Property<string>("TenDem")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenDem");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("IdCV");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MaSp");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("TenSP");

                    b.HasKey("Id");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("_1.DAL.Models.BangChiTietSanPham", b =>
                {
                    b.HasOne("_1.DAL.Models.BangHangSanPham", "HangSP")
                        .WithMany()
                        .HasForeignKey("IdHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangLoaiSP", "LoaiSP")
                        .WithMany()
                        .HasForeignKey("IdLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangMauSac", "MauSac")
                        .WithMany()
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangSanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("IdSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HangSP");

                    b.Navigation("LoaiSP");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("_1.DAL.Models.BangDoiTra", b =>
                {
                    b.HasOne("_1.DAL.Models.BangKhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Id")
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangHoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("Id")
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("_1.DAL.Models.BangGioHang", b =>
                {
                    b.HasOne("_1.DAL.Models.BangKhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangNhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("_1.DAL.Models.BangGioHangChiTiet", b =>
                {
                    b.HasOne("_1.DAL.Models.BangChiTietSanPham", "CTSanPham")
                        .WithMany()
                        .HasForeignKey("IdCTSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangGioHang", "GioHang")
                        .WithMany()
                        .HasForeignKey("IdGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CTSanPham");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("_1.DAL.Models.BangHoaDon", b =>
                {
                    b.HasOne("_1.DAL.Models.BangKhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("IdKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangNhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("_1.DAL.Models.BangHoaDonCT", b =>
                {
                    b.HasOne("_1.DAL.Models.BangChiTietSanPham", "CTSanPham")
                        .WithMany()
                        .HasForeignKey("IDCTSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangKhuyenMai", "KhuyenMai")
                        .WithMany()
                        .HasForeignKey("IDKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.DAL.Models.BangHoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CTSanPham");

                    b.Navigation("HoaDon");

                    b.Navigation("KhuyenMai");
                });

            modelBuilder.Entity("_1.DAL.Models.BangNhanVien", b =>
                {
                    b.HasOne("_1.DAL.Models.BangChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("IdCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });
#pragma warning restore 612, 618
        }
    }
}
